name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run tests
        run: mvn test


      - name: PR title checker
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "GitHub Actions"
        author_email: "actions@github.com"
        message: "PR title formatted correctly"
        signoff: true
        add: "README.md"
        force: true
        match: "regex"
        regex: "PTX-\*: <title>"
