name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17

        - name: Run tests
          run: mvn test
  spotless:
    runs-on: ubuntu-latest
    steps:
      - name: Install Spotless
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install spotless

      - name: Run Spotless
        run: mvn spotless:apply
