name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2

        with:

          distribution: 'temurin'

          java-version: '17'

          cache: 'maven'

      - name: Run test

        run: mvn test
        
      - name: Verify PR title format
        env:
          PR_TITLE_REGEX: 'PTX-\d+: .*'
        run: |
          if ! echo "${{ github.event.pull_request.title }}" | grep -E "${{ env.PR_TITLE_REGEX }}"; then
            echo "Error: PR title does not match required format (${PR_TITLE_REGEX})" >&2
            exit 1
          fi
        
        
 
