name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17

        - name: Run tests
          run: mvn test
        - name: Verify PR title format
          env:
            PR_TITLE_REGEX: 'PTX-\d+: .*'
          run: |
            if ! echo "${{ github.event.pull_request.title }}" | grep -qE "${{ env.PR_TITLE_REGEX }}"; then
              echo "Error: PR title does not match required format (${PR_TITLE_REGEX})" >&2
              exit 1
            fi
        - name: Run Spotless
          run: mvn spotless:apply
 
