name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2

        with:

          distribution: 'temurin'

          java-version: '17'

          cache: 'maven'

      - name: Run test

        run: mvn test
        
      - name: Check PR Title
        run: |
          title= ${{ github.event.pull_request.title }}
          regex="PTX-.*: <title>"
          if [[ "$title" =~ $regex ]]; then
            echo "PR Title is valid"
          else
            echo "PR Title is invalid"
            exit 1
          fi

        
 
