name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2

        with:

          distribution: 'temurin'

          java-version: '17'

          cache: 'maven'

      - name: code formatting

        run: mvn spotless:check

      - name: Run test

        run: mvn test
        
        
 
