name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Maven
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Install Spotless
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install spotless

      - name: Run Spotless
        run: mvn spotless:apply
